LogisticRegression:
  penalty: ['l1', 'l2']
  C: [5, 2, 1, 0.1, 0.05, 0.03, 0.0275,0.025, 0.02 , 0.01, 0.009, 0.0075, 0.005, 0.001]
  class_weight: ['balanced',]
  random_state: [100,200, 300, 400, 500]
  max_iter: [1, 2, 3, 4, 5, 10, 15, 20, 30, 50, 80, 100]
  fit_intercept: [True, True]
  intercept_scaling: [True]
  tol: [0.1, 0.075, 0.05 ,0.01, 0.001, 0.0002, 0.0001, 0.00005, 0.00001]
  n_jobs: [-1]
RandomForestClassifier:
  n_estimators: [20, 50, 100, 200]
  max_features: [5, 10, 15, 20]
  criterion : ['gini', 'entropy']
  max_depth: [20, 50, 80, 100]
  random_state: [100,200, 300, 400, 500]
  min_samples_split: [2, 3, 5, 7]
  class_weight: ['balanced', 'balanced_subsample',]
  n_jobs: [-1]
SVM:
  C: [5, 2, 1, 0.1, 0.01, 0.001, 0.0005, 0.0001]
  kernel: ['rbf', 'linear']
  degree: [2, 3]
  gamma: [1, 0.1, 0.01, 0.001]
  probability: [True, False]
  tol: [0.1, 0.075, 0.05 ,0.01, 0.001, 0.0002, 0.0001, 0.00005, 0.00001]
  class_weight: ['balanced', ]
  max_iter: [20, 50, 100, 150, 200]
  random_state: [100, 200, 300, 400, 500]
  decision_function_shape : ['ovr', 'ovo']
LinearRegression:
  fit_intercept: [True]
  n_jobs: [-1]
RandomForestRegressor:
  n_estimators: [20, 50, 100, 200]
  criterion: ['mse', 'mae']
  max_features: [5, 10, 15, 20]
  max_depth: [20, 50, 80, 100]
  random_state: [100,200, 300, 400, 500]
  min_samples_split: [2, 3, 5, 7]
  n_jobs: [-1]
SVR:
  C: [5, 2, 1, 0.1, 0.01, 0.001, 0.0005, 0.0001]
  epsilon: [0.1, 0.5, 1]
  kernel: ['rbf', 'poly']
  degree: [2]
  gamma: [1, 0.1, 0.01, 0.001]
  tol: [0.1, 0.075, 0.05 ,0.01, 0.001, 0.0002, 0.0001, 0.00005, 0.00001]
  max_iter: [20, 50, 100, 150, 200]

